version: '3'

services:
        dsi-runtime:
                image: $DSI_IMAGE
                hostname: dsi-runtime
                domain: dsi
                ports:
                        - "${HTTP_PORT}:9080"
                        - "${HTTPS_PORT}:9443"
                command: ["/root/start.sh", $DSI_TEMPLATE]
                environment:
                        - LOGGING_TRACE_SPECIFICATION=$LOGGING_TRACE_SPECIFICATION
                        - DSI_PARTITIONS_COUNT=$DSI_PARTITIONS_COUNT
                volumes:
                        - volume-templates:/opt/dsi/runtime/wlp/templates/servers
                        - volume-solutions:/opt/dsi/runtime/wlp

volumes:
        volume-templates:
        volume-solutions:
