version: '3'

services:
        dsi-runtime:
                image: $DSI_IMAGE
                ports:
                        - "${HTTP_PORT}:9080"
                        - "${HTTPS_PORT}:9443"
                environment:
                        - LOGGING_TRACE_SPECIFICATION=$LOGGING_TRACE_SPECIFICATION
